name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          name: id_rsa
          known_hosts: "just-a-placeholder-so-we-dont-get-asked"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ec2-user/Netflix-Lite
            git pull origin main
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            
            docker-compose up --build -d
          EOF
